stages:
  - build
  - prepare_image
  - test

Prepare Docker Image:
  stage: prepare_image
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker run -v ${SHARED_PATH}:/mnt ubuntu ls /mnt
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  after_script:
    - docker logout ${CI_REGISTRY}
  tags:
    - docker
  only:
    changes:
      - Dockerfile

Build:
  image: gradle:jdk11
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

Test:
  stage: test
  image: gradle:jdk11
  script:
    - chmod +x gradlew
    - ./gradlew test

